### ISSUE TITLE
Implement `gem install --verify-signatures` as an alias of `gem verify` + `gem install`.

### ISSUE THREAD

**Issue by rochlefebvre** [Shopify/ruby-sigstore#34]
We currently have a stub implementation for `verify_extend.rb`.  The `pre_install` hook should be fleshed out to call `GemVerifier.run` and return from `pre_install` accordingly.

`--verify-signatures` makes sense to me, moreso than `--verify`, but consider whether that's true.

**Comment by jchestershopify** [comment]
Is this still planned in light of #35 and #51?

**Comment by jchestershopify** [comment]
Looking at this again today: it predates #35 and #51, where we decided to update the UI to be built around `gem signatures`. To avoid stray issues I'm going to close this one.
