### ISSUE TITLE
Implement `gem build --sign` as an alias of `gem build` + `gem sign`.

### ISSUE THREAD

**Issue by rochlefebvre** [Shopify/ruby-sigstore#38]
The `sign_extend` file implements much of the functionality already, but it was written early on in the project.  It is not tested.

We should review the code and follow the patterns from `sign_command`.

**Comment by doodzik** [comment]
I tested the code today and it works as expected. When [I refactored the code](https://github.com/Shopify/ruby-sigstore/pull/9/files) I made sure both `sign_extend` and `sign_command` work as expected.
